name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root
        run: npm ci

      - name: Lint (if exists)
        run: npm run lint --if-present

      - name: Test (if exists)
        run: npm test --if-present

      - name: Build web
        run: npm run build

      - name: Install functions (if folder exists)
        if: ${{ hashFiles('functions/package.json') != '' }}
        run: |
          cd functions
          npm ci

      - name: Build functions (if script exists)
        if: ${{ hashFiles('functions/package.json') != '' }}
        run: |
          cd functions
          npm run build --if-present
